const { ObjectId } = require('mongodb');
const DateHelper = require('../lib/date-helpers');

class Service {

    constructor(db) {
        this.db = db;
        this.collection = "";
        this.fields_white_list = new Set();
    }

    async getBy(query, options = {}) {
        try {
            return await this.db.collection(this.collection).findOne(query, options);
        } catch (err) {
            console.error(err.stack);
            throw err;
        }
    }

    async getList(query, options = {}) {
        try {
            return await this.db.collection(this.collection).find(query, options).toArray();
        } catch (err) {
            console.error(err.stack);
            throw err;
        }
    }

    getById(id) {
        if (!(id instanceof ObjectId)) {
            id = ObjectId(id);
        }
        return this.getBy({ _id: id });
    }

    async updateBy(field, value, data) {
        try {
            // if it exist remove _id field from data
            if (data._id) {
                delete data._id;
            }

            return await this.db.collection(this.collection).updateOne({
                [field]: value
            }, { $set: data });
        } catch (err) {
            console.error(err.stack);
            throw err;
        }
    }

    async create(data, options = {}) {
        try {
            const session = options.session;
            // add a sluf field generated by `${Math.random().toString(36).substring(2, 15)}-${Date.now().toString(36)}`
            const now = DateHelper.toISO8601(DateHelper.nowUtc());
            const filteredData = {
                ...this.filterWhiteListedFields(data, this.fields_white_list),
                slug: `${Math.random().toString(36).substring(2, 15)}-${Date.now().toString(36)}`,
                updated_at: now,
                created_at: now,
            };

            let result = null;
            if (session) {
                result = await this.db.collection(this.collection).insertOne(filteredData, { session });
            } else {
                result = await this.db.collection(this.collection).insertOne(filteredData);
            }
            filteredData._id = result.insertedId;
            return filteredData;
        } catch (err) {
            console.error(err.stack);
            throw err;
        }
    }


    async deleteBy(field, value) {
        try {
            const result = await this.db.collection(this.collection).deleteOne({
                [field]: value
            });
            return result;
        } catch (err) {
            console.error(err.stack);
            throw err;
        }
    }

    async existsBy(field, value) {
        try {
            const result = await this.db.collection(this.collection).findOne({
                [field]: value
            });
            return !!result;
        } catch (err) {
            console.error(err.stack);
            throw err;
        }
    }


    filterWhiteListedFields(data, fields_white_list) {

        const filteredData = {};

        for (const field of Object.keys(data)) {
            if (!fields_white_list.has(field)) {
                console.log(`Field filtered out by filterWhiteListedFields: ${field}`);
            } else {
                filteredData[field] = data[field];
            }
        }

        return filteredData;
    }
}

module.exports = Service;